version: 2

models:
  - name: stg_events
    description: >
      Data about events in the platform of Greenery.
    columns:
      - name: event_id
        description: >
          UUID of each unique event on the platform.
        tests:
          - not_null
          - unique
      - name: session_id
        description: >
          UUID of each browsing session on the platform which can contain many events.
        tests:
          - not_null
      - name: user_id
        description: >
          UUID of the user that this event is associated with.
        tests:
          - not_null
          - relationships:
                to: ref('stg_users')
                field: user_id     
      - name: page_url
        description: >
          URL that the event happened on.
        tests:
          - not_null
      - name: created_at_utc
        description: >
          Timestamp of the event (UTC).
        tests:
          - not_null
      - name: event_type
        description: >
          Type of event.
        tests:
          - not_null
      - name: order_id
        description: >
          If the event is specific to an order (mostly used for checkout).
        test:
          - relationships:
                to: ref('stg_orders')
                field: order_id 
      - name: product_id
        description: >
          If the event is specific to a product.
        test:
          - relationships:
                to: ref('stg_products')
                field: product_id