version: 2

models:
  - name: base_promos
    description: >
      Add Hash like promo_id with the goal that not use the promo name for the joins.
    columns:
      - name: promo_id
        description: >
          Each unique promocode on platform (Hash).
        tests:
          - not_null
          - unique
      - name: name_promo
        description: >
          Promocode on platform.
        tests:
          - not_null
          - unique       
      - name: total_discount_usd
        description: >
          Absolute dollar amount that is given off with the code.
        tests:
          - not_null
          - positive_values
      - name: status_promo
        description: >
          Is the promo code active or disabled.
        tests:
          - not_null
          - accepted_values:
                    values: ['inactive','active']
      - name: date_load
        description: >
          Date that the data was loaded.
        tests:
          - not_null